@host = http://localhost:5406


### Request token

# @prompt userid Custom id or empty for a random id

GET http://localhost:54062/v1/tokens?userid={{userid}}


### Register debit

# @prompt token Bearer token

POST {{host}}/debit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "registrationDate": "2024-09-05T12:27:13.000Z",
  "value": "100.99"
}


### Register credit

# @prompt token Bearer token

POST {{host}}/credit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "registrationDate": "2024-09-05T13:47:34.000Z",
  "value": "99.99"
}


### Get day's balance

# @prompt token Bearer token
# @prompt day 0000-00-00

GET {{host}}/balance?day={{day}}
Content-Type: application/json
Authorization: Bearer {{token}}
