services:

  accounting-operations-db:
    container_name: merchant-accounting-system-accounting-operations-db
    image: postgres:16.4-bookworm
    ports:
      - 5401:5432
    volumes:
      - ./.data/accounting-operations:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ab58f518b0f8485a8934ee11289b4f31
      - POSTGRES_PASSWORD=62561b6debea489bae1802bcd0590bc0
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  daily-balances-db:
    container_name: merchant-accounting-system-daily-balance-db
    image: postgres:16.4-bookworm
    ports:
      - 5402:5432
    volumes:
      - ./.data/daily-balance:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=e5f413a7aa384eb0b67bd73afa32464f
      - POSTGRES_PASSWORD=45d9bef04dcf4b60b719fbd2a3c129c7
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  message-broker:
    container_name: merchant-accounting-system-message-broker
    image: rabbitmq:3.13-management
    ports:
      - 54031:15672
      - 5403:5672
    environment:
      - RABBITMQ_DEFAULT_USER=db7d825c5ba9451381c4aa5c91f7bf82
      - RABBITMQ_DEFAULT_PASS=9219052054e74abf95b964c37361cc4c
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 30s
      retries: 3

  accounting-operations-migrate:
    container_name: merchant-accounting-system-accounting-operations-migrate
    build:
      context: ./services/accounting-operations/src
      dockerfile: ./Cli/Dockerfile
    command: migrate -c "Server=accounting-operations-db;Port=5432;Database=accounting-operations;User Id=ab58f518b0f8485a8934ee11289b4f31;Password=62561b6debea489bae1802bcd0590bc0;"
    depends_on:
      accounting-operations-db:
        condition: service_healthy

  daily-balances-migrate:
    container_name: merchant-accounting-system-daily-balances-migrate
    build:
      context: ./services/daily-balances/src
      dockerfile: ./Cli/Dockerfile
    command: migrate -c "Server=daily-balances-db;Port=5432;Database=daily-balances;User Id=e5f413a7aa384eb0b67bd73afa32464f;Password=45d9bef04dcf4b60b719fbd2a3c129c7;"
    depends_on:
      daily-balances-db:
        condition: service_healthy

  accounting-operations-api:
    container_name: merchant-accounting-system-accounting-operations-api
    build:
      context: ./services/accounting-operations/src
      dockerfile: ./Api/Dockerfile
    ports:
      - 5404:8080
    depends_on:
      daily-balances-api:
        condition: service_healthy
    environment:
      - ConnectionStrings__Operations=Server=accounting-operations-db;Port=5432;Database=accounting-operations;User Id=ab58f518b0f8485a8934ee11289b4f31;Password=62561b6debea489bae1802bcd0590bc0;
      - MessageBroker__Host=amqp://message-broker:5672
      - MessageBroker__Username=db7d825c5ba9451381c4aa5c91f7bf82
      - MessageBroker__Password=9219052054e74abf95b964c37361cc4c
    healthcheck:
      test: curl -fv http://127.0.0.1:8080/live
      interval: 15s
      timeout: 30s
      retries: 3

  daily-balances-api:
    container_name: merchant-accounting-system-daily-balances-api
    build:
      context: ./services/daily-balances/src
      dockerfile: ./Api/Dockerfile
    ports:
      - 5405:8080
    depends_on:
      daily-balances-db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    environment:
      - ConnectionStrings__Balances=Server=daily-balances-db;Port=5432;Database=daily-balances;User Id=e5f413a7aa384eb0b67bd73afa32464f;Password=45d9bef04dcf4b60b719fbd2a3c129c7;
    healthcheck:
      test: curl -fv http://127.0.0.1:8080/live
      interval: 15s
      timeout: 30s
      retries: 3

  operations-consumer-worker:
    container_name: merchant-accounting-system-operations-consumer-worker
    build:
      context: ./services/daily-balances/src
      dockerfile: ./OperationsConsumer/Dockerfile
    depends_on:
      daily-balances-db:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    environment:
      - ConnectionStrings__Balances=Server=daily-balances-db;Port=5432;Database=daily-balances;User Id=e5f413a7aa384eb0b67bd73afa32464f;Password=45d9bef04dcf4b60b719fbd2a3c129c7;
      - MessageBroker__Host=amqp://message-broker:5672
      - MessageBroker__Username=db7d825c5ba9451381c4aa5c91f7bf82
      - MessageBroker__Password=9219052054e74abf95b964c37361cc4c

  simple-auth-api:
    container_name: merchant-accounting-system-simple-auth-api
    build:
      context: ./services/simple-auth/src
      dockerfile: ./Api/Dockerfile
    ports:
      - 54062:8080
    environment:
      - Authority__Url=http://api-gateway:8001/consumers/apigatewayuser/jwt
      - Authority__Secret=SZfI0j8zz7UtJSbIqfDhPaBEX4d8bWDo
    depends_on:
      api-gateway:
        condition: service_healthy
    healthcheck:
      test: curl -fv http://127.0.0.1:8080/live
      interval: 15s
      timeout: 30s
      retries: 3

  api-gateway:
    container_name: merchant-accounting-system-api-gateway
    image: kong/kong-gateway:3.7.1.2
    volumes:
      - ./configuration/kong:/kong/declarative/
    ports:
      - 5406:8000
      - 54061:8001
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    depends_on:
      accounting-operations-api:
        condition: service_healthy
      daily-balances-api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
