@host = http://localhost:5290
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.mvdjdBZKOtWyQl54xAd8C9kY0RUyq-z26qNTjFR1DKA

### Get day's balance

# @prompt day 0000-00-00

GET {{host}}/v1/balances?day={{day}}
Content-Type: application/json
Authorization: Bearer {{token}}
